In [1]:
#!pip install numpy

In [2]:
#!pip install pandas

In [3]:
#!pip list

In [4]:
#!pip install ipykernel

In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
df_1=pd.read_csv('Enron.csv')
df_1.head(25)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0
10,fw : txu lone star pipeline standard pooling a...,- - - - - original message - - - - -\r\nfrom :...,0
11,"enron / hpl nom for december 1 , 2000",( see attached file : hplnl 201 . xls )\r\n- h...,0
12,"hpl nom . for may 26 - 29 , 2001",( see attached file : hplno 526 . xls )\r\n- h...,0
13,"enron / hpl actuals for november 13 , 2000",teco tap 120 . 000 / hpl gas daily\r\nls hpl l...,0
14,txu noms . for 10 / 14 - 16 / 00,"attached , please find the txu nominations for...",0
15,"hpl nom for april , 2001",( see attached file : hplno 410 . xls )\r\n- h...,0
16,i spoke with the person who confirms pg & e on...,brian agrees with our ( tufco and ena ) number...,0
17,re : noms / actual vols for 3 / 26 / 01,"eileen , our gas control records indicate the ...",0
18,"hpl nom for march 27 , 2001",( see attached file : hplno 327 . xls )\r\n- h...,0
19,"estimated actuals for april 5 , 2001",estimated actuals\r\nteco tap 24 . 917\r\nwhen...,0
20,re : nom / alloc for june 6 th,"we agree\r\n"" eileen ponton "" on 06 / 07 / 200...",0
21,"enron / hpl actuals for march 28 , 2001","estimated actual for march 28 , 2001\r\nteco t...",0
22,"hpl nom for march 30 , 2001",( see attached file : hplno 330 . xls )\r\n- h...,0
23,"hpl nominations for march 31 , 2001 and april ...",( see attached file : hplno 401 . xls ) ( see ...,0
24,txu contract search,"anthony ,\r\ndaren farmer on the texas desk ca...",0

In [8]:
df_2=pd.read_csv('Ling.csv')
df_2.head(25)

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0
5,call for abstracts : optimality in syntactic t...,content - length : 4437 call for papers is the...,0
6,m . a . in scandinavian linguistics,m . a . in scandinavian linguistics at the uni...,0
7,call for papers : linguistics session of the m...,call for papers linguistics session - - midwes...,0
8,foreign language in commercials,content - length : 1937 greetings ! i ' m wond...,0
9,fulbright announcement : please post / dissemi...,fulbright announcement : please post / dissemi...,0
10,gala ' 95 : call for papers,groningen assembly on language acquisition 199...,0
11,bu conf on language development ' 95 - announc...,20th annual boston university conference on la...,0
12,korean software for macintosh,"dear sir / madam , would you please send me an...",0
13,NaN,syntax the antisymmetry of syntax richard s . ...,0
14,simultaneous prepositions and postpositions in...,i ' m looking for analyses of nominal construc...,0
15,sum : imperatives without you subjects,content - length : 3573 summary of responses t...,0
16,policies,moderators ' message a very happy 1995 to all ...,0
17,* * * correction to hellenistic greek announce...,a couple of days ago i send an fyi on hellenis...,0
18,question on audio samples,i am looking for audio samples of english spee...,0
19,sexism and language,"re lydie e . meunier 's latest , i did not mea...",0
20,teaching english in korea,teaching english in korea the language center ...,0
21,free,this is a multi-part message in mime format . ...,1
22,email address for w . dressler,colleagues - we are trying to contact wolfgang...,0
23,"dhumbadji ! , journal for the history of language","good news for all subscribers , the december i...",0
24,question : quantitative information,"hello , there is someone who knows where can i...",0

In [9]:
print(df_1.shape)

(29767, 3)

In [10]:
df_1.head()

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0

In [11]:
df_1.tail()

,subject,body,label
29762,confidence is back,"hello ,\r\nmy boyfriend began having problems ...",1
29763,important information,love - potion for your darling is all you want...,1
29764,vys - make itnger,you have feelings of guilt and embarrassment ...,1
29765,the best thing come in large parcels,spur - m formula\r\nincrease sperm production ...,1
29766,it works amaziing,"hello , welcome to the medzonlin claiming e\r\...",1

In [12]:
print(df_2.shape)

(2859, 3)

In [13]:
df_2.head()

,subject,body,label
0,job posting - apple-iss research center,content - length : 3386 apple-iss research cen...,0
1,NaN,"lang classification grimes , joseph e . and ba...",0
2,query : letter frequencies for text identifica...,i am posting this inquiry for sergei atamas ( ...,0
3,risk,a colleague and i are researching the differin...,0
4,request book information,earlier this morning i was on the phone with a...,0

In [14]:
df_2.tail()

,subject,body,label
2854,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
2855,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
2856,anglicization of composers ' names,"judging from the return post , i must have sou...",0
2857,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
2858,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0

In [15]:
# merge two dataframes df_1 & df_2
df_merge= pd.concat([df_1, df_2], ignore_index=True)

In [16]:
print(df_merge.shape)

(32626, 3)

In [17]:
df_merge.head(50)

,subject,body,label
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0
5,hpl nom for may 31 2001,( see attached file : hplno 531 . xls )\r\n- h...,0
6,# 9760,tried to get fancy with your address and it ca...,0
7,"hpl noms for february 15 , 2000",( see attached file : hplo 215 . xls )\r\n- hp...,0
8,fw : pooling contract template,- - - - - original message - - - - -\r\nfrom :...,0
9,"hpl nom for march 28 , 2000",( see attached file : hplo 328 . xls )\r\n- hp...,0
10,fw : txu lone star pipeline standard pooling a...,- - - - - original message - - - - -\r\nfrom :...,0
11,"enron / hpl nom for december 1 , 2000",( see attached file : hplnl 201 . xls )\r\n- h...,0
12,"hpl nom . for may 26 - 29 , 2001",( see attached file : hplno 526 . xls )\r\n- h...,0
13,"enron / hpl actuals for november 13 , 2000",teco tap 120 . 000 / hpl gas daily\r\nls hpl l...,0
14,txu noms . for 10 / 14 - 16 / 00,"attached , please find the txu nominations for...",0
15,"hpl nom for april , 2001",( see attached file : hplno 410 . xls )\r\n- h...,0
16,i spoke with the person who confirms pg & e on...,brian agrees with our ( tufco and ena ) number...,0
17,re : noms / actual vols for 3 / 26 / 01,"eileen , our gas control records indicate the ...",0
18,"hpl nom for march 27 , 2001",( see attached file : hplno 327 . xls )\r\n- h...,0
19,"estimated actuals for april 5 , 2001",estimated actuals\r\nteco tap 24 . 917\r\nwhen...,0
20,re : nom / alloc for june 6 th,"we agree\r\n"" eileen ponton "" on 06 / 07 / 200...",0
21,"enron / hpl actuals for march 28 , 2001","estimated actual for march 28 , 2001\r\nteco t...",0
22,"hpl nom for march 30 , 2001",( see attached file : hplno 330 . xls )\r\n- h...,0
23,"hpl nominations for march 31 , 2001 and april ...",( see attached file : hplno 401 . xls ) ( see ...,0
24,txu contract search,"anthony ,\r\ndaren farmer on the texas desk ca...",0
25,re : nom / vols for 3 / 24 thru 3 / 26 / 01,"we agree\r\n"" eileen ponton "" on 03 / 26 / 200...",0
26,"hpl nom for march 28 , 2001",( see attached file : hplno 328 . xls )\r\n- h...,0
27,re : noms / actual vols for 3 / 28 / 01,"we agree\r\n"" eileen ponton "" on 03 / 29 / 200...",0
28,re : tufco deal 108058,"let me look into it , will get back with you a...",0
29,"hpl nom for march 29 , 2001",( see attached file : hplno 329 . xls )\r\n- h...,0
30,"hpl nom for april 3 , 2001",( see attached file : hplno 403 . xls )\r\n- h...,0
31,re : noms / actual flow for 3 / 29 / 01,"we agree with the nomination .\r\n"" eileen pon...",0
32,fw : txu fuel deals imbalances,"daren ,\r\nthe deals listed below are related ...",0
33,re : noms / actual flow for 3 / 22 / 01,"we agree with the nomination .\r\n"" eileen pon...",0
34,inter / intra gisb for enron north america,i forwarded these contract forms to you on may...,0
35,txu fuel company,we cannot enter into a contract with txu as th...,0
36,re : noms / actual flow for 3 / 21 / 01,"we agree with the nomination .\r\nccs\r\n"" eil...",0
37,re : gisb contracts for intrastate and interst...,"mr . farmer ,\r\ni have forwarded your request...",0
38,re : noms for 6 / 20 thru 6 / 24 / 01,"we agree with the volumes . thank you .\r\n"" e...",0
39,re : noms / actuals for june 11 th & 12 th,"we agree\r\n"" eileen ponton "" on 06 / 13 / 200...",0
40,re : noms / actual flow for 03 / 20 / 01,"we agree with the nominations .\r\n"" eileen po...",0
41,"hpl nom for march 24 - 26 , 2001",( see attached file : hplno 324 . xls )\r\n- h...,0
42,"hpl nom for march 22 , 2001",( see attached file : hplno 322 . xls )\r\n- h...,0
43,txu fuels / sds nomination for april 2001,attached is the april 2001 nomination for our ...,0
44,"hpl nom for march 22 , 2001",( see attached file : hplno 323 . xls )\r\n- h...,0
45,txu fuel deal # 789355,please verify the price for txu fuel deal # 78...,0
46,"enron / hpl actuals for december 11 , 2000",teco tap 30 . 000 / enron ; 120 . 000 / hpl ga...,0
47,"enron / hpl actuals for december 6 , 2000",teco tap 29 . 167 / hpl iferc\r\nls hpl lsk ic...,0
48,"hpl nom for march 21 , 2001",( see attached file : hplno 321 . xls )\r\n- h...,0
49,"hpl nom for march 17 , 2001",( see attached file : hplno 317 . xls )\r\n- h...,0

In [18]:
df_merge.tail()

,subject,body,label
32621,win $ 300usd and a cruise !,"raquel 's casino , inc . is awarding a cruise ...",1
32622,you have been asked to join kiddin,"the list owner of : "" kiddin "" has invited you...",1
32623,anglicization of composers ' names,"judging from the return post , i must have sou...",0
32624,"re : 6 . 797 , comparative method : n - ary co...",gotcha ! there are two separate fallacies in t...,0
32625,re : american - english in australia,hello ! i ' m working on a thesis concerning a...,0

In [19]:
df_merge.to_csv("output.csv", index=False)

In [20]:
df_merge["label"].value_counts()

label
0    18192
1    14434
Name: count, dtype: int64

In [21]:
!pip install nltk

Requirement already satisfied: nltk in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (3.9.4)
Requirement already satisfied: click in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in d:\2. cyber security\term project\new folder\cybersec_1\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
#def preprocess(text):
    # 1. lowercase
    #text = text.lower()
    
    # 2. remove punctuation
    #import string
    #text = ''.join(c for c in text if c not in string.punctuation)
    
    # 3. tokenize
    #from nltk import word_tokenize
    #words = word_tokenize(text)
    
    # 4. POS tagging
    #from nltk import pos_tag
    #tagged = pos_tag(words)
    
    # 5. lemmatization
    #from nltk.stem import WordNetLemmatizer
    #from nltk.corpus import wordnet
    
    #def get_wordnet_pos(tag):
        #if tag.startswith('J'):
            #return wordnet.ADJ
        #elif tag.startswith('V'):
            #return wordnet.VERB
        #elif tag.startswith('N'):
            #return wordnet.NOUN
        #elif tag.startswith('R'):
            #return wordnet.ADV
        #else:
            #return wordnet.NOUN
    
    #lemmatizer = WordNetLemmatizer()
    #lemmas = [lemmatizer.lemmatize(w, get_wordnet_pos(t)) for w, t in tagged]
    
    # 6. remove stopwords (LAST)
    #from nltk.corpus import stopwords
    #stop_words = set(stopwords.words('english'))
    #cleaned = [w for w in lemmas if w not in stop_words]
    
    #return ' '.join(cleaned)

In [23]:
df_merge.isnull().sum()

subject    260
body         0
label        0
dtype: int64

In [24]:
df_merge["subject_missing"] = df_merge["subject"].isnull()
df_merge[df_merge["subject_missing"] == True]

,subject,body,label,subject_missing
3517,NaN,the only fix to penis growth\r\nlimited time o...,1,True
3524,NaN,a permanent solution to penis growth\r\nlimite...,1,True
3540,NaN,a only fix to penis enlargement\r\nlimited tim...,1,True
3543,NaN,the only solution to penis growth\r\nlimited t...,1,True
3566,NaN,html\r\nbody\r\npbr\r\n/ p\r\np align = center...,1,True
...,...,...,...,...
32042,NaN,the latest issue ( 1994 n01 ) of etudes de let...,0,True
32055,NaN,b a r g a i n a i r f a r e s your 1 - stop tr...,1,True
32297,NaN,"data to : = 20 date : fri , 06 feb 1998 22 : 3...",1,True
32303,NaN,"epac . pt , e . carnoali @ genie . com , e . c...",1,True
32546,NaN,simply send a message to : listserv @ tamvm1 ....,0,True

In [25]:
df_merge["subject"] = df_merge["subject"].fillna("")

In [26]:
df_merge["subject"].isnull().sum()

np.int64(0)

In [27]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [28]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ANT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
import string
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) - {"not", "no", "nor"}

def preprocess(text):
    # lowercase
    text = text.lower()
    
    # remove punctuation
    text = ''.join(c for c in text if c not in string.punctuation)
    
    # simple tokenization (split)
    words = text.split()
    
    # remove stopwords
    words = [w for w in words if w not in stop_words]
    
    return ' '.join(words)

In [30]:
# 2. combine
df_merge["text"] = df_merge["subject"] + " " + df_merge["body"]

In [31]:
# 3. preprocess text
df_merge["clean_text"] = df_merge["text"].apply(preprocess)

In [32]:
df_merge.head()

,subject,body,label,subject_missing,text,clean_text
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0,False,"hpl nom for may 25 , 2001 ( see attached file ...",hpl nom may 25 2001 see attached file hplno 52...
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0,False,re : nom / actual vols for 24 th - - - - - - -...,nom actual vols 24 th forwarded sabrae zajac h...
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0,False,"enron actuals for march 30 - april 1 , 201 est...",enron actuals march 30 april 1 201 estimated a...
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0,False,"hpl nom for may 30 , 2001 ( see attached file ...",hpl nom may 30 2001 see attached file hplno 53...
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0,False,"hpl nom for june 1 , 2001 ( see attached file ...",hpl nom june 1 2001 see attached file hplno 60...

In [33]:
print(df_merge.shape)

(32626, 6)

In [34]:
df_3=pd.read_csv('CEAS_08.csv')
df_3.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

In [35]:
df_4=pd.read_csv('Nazario.csv')
df_4.head()

,sender,receiver,date,subject,body,urls,label
0,Mail System Internal Data <MAILER-DAEMON@monke...,NaN,28 Sep 2017 09:57:25 -0400,DON'T DELETE THIS MESSAGE -- FOLDER INTERNAL DATA,This text is part of the internal format of yo...,1,1
1,cPanel <service@cpanel.com>,jose@monkey.org,"Fri, 30 Oct 2015 00:00:48 -0500",Verify Your Account,Business with \t\t\t\t\t\t\t\tcPanel & WHM \t...,1,1
2,Microsoft Outlook <recepcao@unimedceara.com.br>,NaN,"Fri, 30 Oct 2015 06:21:59 -0300 (BRT)",Helpdesk Mailbox Alert!!!,Your two incoming mails were placed on pending...,1,1
3,Ann Garcia <AnGarcia@mcoe.org>,"""info@maaaaa.org"" <info@maaaaa.org>","Fri, 30 Oct 2015 14:54:33 +0000",IT-Service Help Desk,Password will expire in 3 days. Click Here To ...,0,1
4,"""USAA"" <usaaacctupdate@sccu4u.com>",Recipients <usaaacctupdate@sccu4u.com>,"Fri, 30 Oct 2015 14:02:33 -0500",Final USAA Reminder - Update Your Account Now,"To ensure delivery to your inbox, please add U...",1,1

In [36]:
df_5=pd.read_csv('Nigerian_Fraud.csv')
df_5.head()

,sender,receiver,date,subject,body,urls,label
0,MR. JAMES NGOLA. <james_ngola2002@maktoob.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 02:38:20 +0000",URGENT BUSINESS ASSISTANCE AND PARTNERSHIP,FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,0,1
1,Mr. Ben Suleman <bensul2004nng@spinfinder.com>,R@M,"Thu, 31 Oct 2002 05:10:00 -0000",URGENT ASSISTANCE /RELATIONSHIP (P),"Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",0,1
2,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:17:55 +0100",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
3,PRINCE OBONG ELEME <obong_715@epatra.com>,webmaster@aclweb.org,"Thu, 31 Oct 2002 22:44:20 -0000",GOOD DAY TO YOU,FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,0,1
4,Maryam Abacha <m_abacha03@www.com>,R@M,"Fri, 01 Nov 2002 01:45:04 +0100",I Need Your Assistance.,"Dear sir, \n \nIt is with a heart full of hope...",0,1

In [37]:
df_6=pd.read_csv('SpamAssasin.csv')
df_6.head()

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1

In [38]:
print(df_3.shape)

(39154, 7)

In [39]:
print(df_4.shape)

(1565, 7)

In [40]:
print(df_5.shape)

(3332, 7)

In [41]:
print(df_6.shape)

(5809, 7)

In [42]:
# merge 4 dataframes df_3,df_4,df_5,df_6
df_merge_1= pd.concat([df_3, df_4, df_5, df_6], ignore_index=True)

In [43]:
df_merge_1.head()

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1

In [44]:
print(df_merge_1.shape)

(49860, 7)

In [45]:
df_merge_1.isnull().sum()

sender       331
receiver    2092
date         483
subject       87
body           1
label          0
urls           0
dtype: int64

In [46]:
df_merge_1["subject"] = df_merge_1["subject"].fillna("")
df_merge_1["body"] = df_merge_1["body"].fillna("")

In [47]:
df_merge_1["sender"] = df_merge_1["sender"].fillna("unknown_sender")
df_merge_1["receiver"] = df_merge_1["receiver"].fillna("unknown_receiver")

In [48]:
df_merge_1.isnull().sum()

sender        0
receiver      0
date        483
subject       0
body          0
label         0
urls          0
dtype: int64

In [49]:
df_merge_1[df_merge_1["date"].isnull()]

,sender,receiver,date,subject,body,label,urls
39705,Please login to your Apple ID from \t\t\t\t...,unknown_receiver,NaN,"https://hurinet.or.ug/webapp/, ,",1,1,0
40725,Barrister tunde dosumu <tunde_dosumu@lycos.com>,unknown_receiver,NaN,Urgent Attention,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
40728,Tunde Dosumu <barrister_td@lycos.com>,unknown_receiver,NaN,Urgent Assistance,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1,1
40738,unknown_sender,oshea@UM,NaN,WANTED FOR FRAUD: Fawwaz Ulaby,"$250,000 FOR INFORMATION:\n\nLEADING TO THE CR...",1,1
40742,edema_mb@phantomemail.com,edema_mb@phantomemail.com,NaN,BUSINESS RELATIONSHIP,FROM: Edema Martins.\nPlot 243 Walter Carringt...,1,1
...,...,...,...,...,...,...,...
44009,unknown_sender,stephen@it.usyd.edu.au,NaN,MES FELICITATIONS...,LOTERIE MONDIALE \n\n\n ...,1,0
44017,unknown_sender,onuoha5a2003@yahoo.co.jp,NaN,From:Miss Grace Onuoha,01 BP 1598 ABIDJAN 01 ...,1,0
44019,unknown_sender,resumes@collarini.com,NaN,INVESTMENT...,"Dear Friend,\n \n Please I would like to ap...",1,0
44032,unknown_sender,R@S,NaN,HOW WOULD YOU USE MY FUND TO HELP THE LESS PRI...,"It is a great honour to write you, after sever...",1,0
44046,michealagu0255@zipmail.com.br,unknown_receiver,NaN,CONTACT GLOBAL MAX SHIPING COMPANY,"Atten: My Dear ,\n \nI have Paid the fee for y...",1,0

In [50]:
#df_merge_1["date"] = pd.to_datetime(df_merge_1["date"], errors="coerce")
df_merge_1["date"] = pd.to_datetime(df_merge_1["date"], errors="coerce", utc=True)

In [51]:
df_merge_1["date"] = df_merge_1["date"].fillna("unknown")

In [52]:
df_merge_1["date"] = df_merge_1["date"].astype(str)

In [53]:
df_merge_1.isnull().sum()

sender      0
receiver    0
date        0
subject     0
body        0
label       0
urls        0
dtype: int64

In [54]:
# 2. combine
df_merge_1["text"] = df_merge_1["sender"]+" "+" "+ df_merge_1["date"]+" "+ df_merge_1["subject"] + " " + df_merge_1["body"]

In [55]:
# 3.preprocess text
df_merge_1["clean_text"] = df_merge_1["text"].apply(preprocess)

In [56]:
df_merge_1.head()

,sender,receiver,date,subject,body,label,urls,text,clean_text
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,2008-08-05 23:31:02+00:00,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1,Young Esposito <Young@iworld.de> 2008-08-05 2...,young esposito youngiworldde 20080805 23310200...
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,2008-08-05 23:31:03+00:00,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1,Mok <ipline's1983@icable.ph> 2008-08-05 23:31...,mok iplines1983icableph 20080805 2331030000 be...
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,2008-08-06 08:28:00+00:00,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1,Daily Top 10 <Karmandeep-opengevl@universalnet...,daily top 10 karmandeepopengevluniversalnetpsi...
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,2008-08-05 23:31:20+00:00,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1,Michael Parker <ivqrnai@pobox.com> 2008-08-05...,michael parker ivqrnaipoboxcom 20080805 233120...
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,2008-08-05 23:31:21+00:00,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1,Gretchen Suggs <externalsep1@loanofficertool.c...,gretchen suggs externalsep1loanofficertoolcom ...

In [57]:
print(df_merge_1.shape)

(49860, 9)

In [58]:
df_merge.head()

,subject,body,label,subject_missing,text,clean_text
0,"hpl nom for may 25 , 2001",( see attached file : hplno 525 . xls )\r\n- h...,0,False,"hpl nom for may 25 , 2001 ( see attached file ...",hpl nom may 25 2001 see attached file hplno 52...
1,re : nom / actual vols for 24 th,- - - - - - - - - - - - - - - - - - - - - - fo...,0,False,re : nom / actual vols for 24 th - - - - - - -...,nom actual vols 24 th forwarded sabrae zajac h...
2,"enron actuals for march 30 - april 1 , 201","estimated actuals\r\nmarch 30 , 2001\r\nno flo...",0,False,"enron actuals for march 30 - april 1 , 201 est...",enron actuals march 30 april 1 201 estimated a...
3,"hpl nom for may 30 , 2001",( see attached file : hplno 530 . xls )\r\n- h...,0,False,"hpl nom for may 30 , 2001 ( see attached file ...",hpl nom may 30 2001 see attached file hplno 53...
4,"hpl nom for june 1 , 2001",( see attached file : hplno 601 . xls )\r\n- h...,0,False,"hpl nom for june 1 , 2001 ( see attached file ...",hpl nom june 1 2001 see attached file hplno 60...

In [59]:
df_merge_1[df_merge_1["date"].str.contains("unknown", na=False)].head()

,sender,receiver,date,subject,body,label,urls,text,clean_text
6279,msvksyhq@bodyandcolor.com,cstheory@gvc.ceas-challenge.cc,unknown,All that beach chicks,Summer is here \n\nhttp://lookresolution.com/?...,1,1,msvksyhq@bodyandcolor.com unknown All that be...,msvksyhqbodyandcolorcom unknown beach chicks s...
7410,mpghaoeq@blumhorst.com,cstheory@gvc.ceas-challenge.cc,unknown,Need no words,Need no words \n\nhttp://spivaka.cn/v/\n\n\n,1,1,mpghaoeq@blumhorst.com unknown Need no words ...,mpghaoeqblumhorstcom unknown need no words nee...
8611,rjjtryw@boxerproperty.com,cstheory@gvc.ceas-challenge.cc,unknown,Sunshine,Olympus mountain \n\nhttp://eitherindependence...,1,1,rjjtryw@boxerproperty.com unknown Sunshine Ol...,rjjtrywboxerpropertycom unknown sunshine olymp...
9600,qoaikmk@boltongrp.com,cstheory@gvc.ceas-challenge.cc,unknown,Beijing 2008,Olympic people \n\nhttp://eitherindependence.c...,1,1,qoaikmk@boltongrp.com unknown Beijing 2008 Ol...,qoaikmkboltongrpcom unknown beijing 2008 olymp...
12253,kywyeayhcmu@bosaship.com,cstheory@gvc.ceas-challenge.cc,unknown,Get hot,"Sun, sea and summer \n\nhttp://eitherindepende...",1,1,"kywyeayhcmu@bosaship.com unknown Get hot Sun,...",kywyeayhcmubosashipcom unknown get hot sun sea...

In [60]:
df_final = pd.concat([
    df_merge[["clean_text", "label"]],
    df_merge_1[["clean_text", "label"]]
], ignore_index=True)

In [61]:
print(df_final.shape)

(82486, 2)

In [62]:
df_final.head()

                                          clean_text  label
0  hpl nom may 25 2001 see attached file hplno 52...      0
1  nom actual vols 24 th forwarded sabrae zajac h...      0
2  enron actuals march 30 april 1 201 estimated a...      0
3  hpl nom may 30 2001 see attached file hplno 53...      0
4  hpl nom june 1 2001 see attached file hplno 60...      0

In [63]:
df_final["label"].value_counts()

label
1    42891
0    39595
Name: count, dtype: int64

# Train Test split

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_final["clean_text"], df_final["label"],
    test_size=0.2, random_state=42, #stratify=df_final["label"]
)

# Vectorization (TF-IDF) Term Frequency-Inverse Document Frequency

In [65]:
#from sklearn.feature_extraction.text import TfidfVectorizer

#vectorizer = TfidfVectorizer()
#X_train_vec = vectorizer.fit_transform(X_train)
#X_test_vec = vectorizer.transform(X_test)

In [66]:
#print(X_train.shape)

In [67]:
#print(X_test.shape)

In [68]:
#print(X_train_vec.shape)

In [69]:
#print(X_test_vec.shape)

In [70]:
#vectorizer.get_feature_names_out()[:20]

In [71]:
#y_train.value_counts()

In [72]:
#y_test.value_counts()

# Vectorization TF_IDF Revised

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    min_df=5,
    max_df=0.95,
    #ngram_range=(1,1) #Only single words,
    ngram_range=(1,2),
    token_pattern=r'\b[a-zA-Z]{2,}\b'
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [74]:
print(X_train_vec.shape)

(65988, 10000)

In [75]:
vectorizer.get_feature_names_out()[:20]

array(['aa', 'aaai', 'aaron', 'aaron kulkis', 'ab', 'abacha', 'abandoned',
       'abandoned sum', 'abc', 'abidjan', 'abidjan cote', 'ability',
       'able', 'able get', 'abrahams', 'abroad', 'absa', 'absence',
       'absolute', 'absolutely'], dtype=object)

In [76]:
print(X_test_vec.shape)

(16498, 10000)

## Train Models

# 1. Multinomial Naive Bayes

In [77]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

nb_model = MultinomialNB(alpha=1)
nb_model.fit(X_train_vec, y_train)

y_pred_nb = nb_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

[[7809  120]
 [ 576 7993]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96      7929
           1       0.99      0.93      0.96      8569

    accuracy                           0.96     16498
   macro avg       0.96      0.96      0.96     16498
weighted avg       0.96      0.96      0.96     16498

In [78]:
# TN (7809) → legit emails correctly classified
# FP (120) → legit → wrongly flagged as phishing ❗
# FN (576) → phishing → missed (VERY IMPORTANT ❗)
# TP (7993) → phishing correctly detected

In [79]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

nb_model = MultinomialNB(alpha=0.1)
nb_model.fit(X_train_vec, y_train)

y_pred_nb = nb_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

[[7818  111]
 [ 562 8007]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      7929
           1       0.99      0.93      0.96      8569

    accuracy                           0.96     16498
   macro avg       0.96      0.96      0.96     16498
weighted avg       0.96      0.96      0.96     16498

In [80]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

nb_model = MultinomialNB(alpha=0.01)
nb_model.fit(X_train_vec, y_train)

y_pred_nb = nb_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

[[7818  111]
 [ 550 8019]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      7929
           1       0.99      0.94      0.96      8569

    accuracy                           0.96     16498
   macro avg       0.96      0.96      0.96     16498
weighted avg       0.96      0.96      0.96     16498

In [81]:
# TN (7818) → legit emails correctly classified
# FP (111) → legit → wrongly flagged as phishing ❗
# FN (550) → phishing → missed (VERY IMPORTANT ❗)
# TP (8019) → phishing correctly detected

# Class 0 = legit
# Precision 0.93 means 93% of emails predicted as legit are correct
# Recall 0.99 means 99% of actual legit emails are correctly identified

# Class 1 = phishing
# Precision 0.99 means 99% of emails predicted as phishing are correct
# Recall 0.93 means 93% of actual phishing emails are correctly identified

# F1-score is the harmonic mean of precision and recall, providing a single metric that balances both. 
# For class 0 (legit), an F1-score of 0.96 indicates a strong performance in correctly identifying legit emails while minimizing false positives. 
# For class 1 (phishing), an F1-score of 0.96 also indicates a strong performance in correctly identifying phishing emails while minimizing false negatives. 
# Overall, these metrics suggest that the model is performing well in distinguishing between legit and phishing emails.


#Class 0 → support = 7929
# Class 1 → support = 8569

# macro avg = (metric_class0 + metric_class1) / 2
# Macro precision = (0.93 + 0.99)/2 = 0.96
# Macro recall = (0.99 + 0.94)/2 = 0.96
# Macro F1-score = (0.96 + 0.96)/2 = 0.96

# weighted avg = (metric0 * support0 + metric1 * support1) / total
# Weighted precision = (0.93*7929 + 0.99*8569) / (7929+8569) = 0.96
# Weighted recall = (0.99*7929 + 0.94*8569) / (7929+8569) = 0.96
# Weighted F1-score = (0.96*7929 + 0.96*8569) / (7929+8569) = 0.96

# 2. Linear SVM

In [82]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(random_state=42)
svm_model.fit(X_train_vec, y_train)

y_pred= svm_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7800  129]
 [  96 8473]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7929
           1       0.99      0.99      0.99      8569

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

In [83]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC
import pandas as pd

# Parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10]
}

# GridSearch
grid_svm = GridSearchCV(
    LinearSVC(random_state=42, max_iter=2000),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_svm.fit(X_train_vec, y_train)

# Best result
print("Best parameters:", grid_svm.best_params_)
print("Best recall:", grid_svm.best_score_)

# Convert results to DataFrame
df = pd.DataFrame(grid_svm.cv_results_)

# Expand params into separate columns
params_df = pd.json_normalize(df['params'])

# Combine with original results
df_full = pd.concat([params_df, df], axis=1)

# Select clean columns
df_results = df_full[['C', 'mean_train_score', 'mean_test_score', 'rank_test_score']]

# Sort by performance
df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)

Best parameters: {'C': 1}
Best recall: 0.9890158264076628

All parameter combinations:
       C  mean_train_score  mean_test_score  rank_test_score
2   1.00          0.998237         0.989016                1
1   0.10          0.993168         0.988812                2
3  10.00          0.999898         0.985316                3
0   0.01          0.985418         0.983043                4

In [84]:
from sklearn.metrics import confusion_matrix, classification_report

# Get best model from GridSearch
best_model = grid_svm.best_estimator_

# Predict on test set
y_pred_svc= best_model.predict(X_test_vec)

# Evaluation
print(confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

[[7800  129]
 [  96 8473]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7929
           1       0.99      0.99      0.99      8569

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

# 3. Random Forest

In [85]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_vec, y_train)

y_pred= rf_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7803  126]
 [ 165 8404]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7929
           1       0.99      0.98      0.98      8569

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498

In [86]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Model
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

# Parameter grid
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 20],
    'min_samples_split': [2, 5]
}

# GridSearch with train scores included
grid_rf = GridSearchCV(
    rf,
    param_grid,
    cv=3,
    scoring='recall',   # keep this for phishing
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_rf.fit(X_train_vec, y_train)

# Best result
print("Best parameters:", grid_rf.best_params_)
print("Best recall:", grid_rf.best_score_)

# Convert results to DataFrame  
df = pd.DataFrame(grid_rf.cv_results_)

# Expand params into separate columns
params_df = pd.json_normalize(df['params'])

# Combine with original results
df_full = pd.concat([params_df, df], axis=1)

# Select clean columns
df_results = df_full[['n_estimators', 'max_depth', 'min_samples_split',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

# Sort by performance
df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)

Best parameters: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
Best recall: 0.9825185521584437

All parameter combinations:
   n_estimators  max_depth  min_samples_split  mean_train_score  \
7           200       20.0                  5          0.994173
6           100       20.0                  5          0.993590
5           200       20.0                  2          0.994814
4           100       20.0                  2          0.993911
1           200        NaN                  2          0.999971
3           200        NaN                  5          0.999956
2           100        NaN                  5          0.999971
0           100        NaN                  2          0.999985

   mean_test_score  rank_test_score
7         0.982519                1
6         0.982285                2
5         0.982082                3
4         0.981790                4
1         0.978119                5
3         0.977857                6
2         0.977041                7
0         0.976575                8

In [87]:
from sklearn.metrics import confusion_matrix, classification_report

# Get best model from GridSearch
best_model = grid_rf.best_estimator_

# Predict on test set
y_pred_rf = best_model.predict(X_test_vec)

# Evaluation
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[7028  901]
 [ 120 8449]]
              precision    recall  f1-score   support

           0       0.98      0.89      0.93      7929
           1       0.90      0.99      0.94      8569

    accuracy                           0.94     16498
   macro avg       0.94      0.94      0.94     16498
weighted avg       0.94      0.94      0.94     16498

# 4. Decision Tree

In [88]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix


dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train_vec, y_train)

y_pred_dt = dt_model.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

[[7514  415]
 [ 354 8215]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.95      7929
           1       0.95      0.96      0.96      8569

    accuracy                           0.95     16498
   macro avg       0.95      0.95      0.95     16498
weighted avg       0.95      0.95      0.95     16498

In [89]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

# Parameter grid
param_grid = {
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# GridSearch (add return_train_score)
grid_dt = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=3,
    scoring='recall',
    return_train_score=True,
    n_jobs=-1
)

# Train
grid_dt.fit(X_train_vec, y_train)

# Best result
print("Best parameters:", grid_dt.best_params_)
print("Best recall:", grid_dt.best_score_)

# Convert results to DataFrame
df = pd.DataFrame(grid_dt.cv_results_)

# Expand params into columns
params_df = pd.json_normalize(df['params'])

# Combine
df_full = pd.concat([params_df, df], axis=1)

# Select relevant columns
df_results = df_full[['max_depth', 'min_samples_split', 'min_samples_leaf',
                      'mean_train_score', 'mean_test_score', 'rank_test_score']]

# Sort
df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)

Best parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best recall: 0.9650661476157499

All parameter combinations:
    max_depth  min_samples_split  min_samples_leaf  mean_train_score  \
4        20.0                  2                 1          0.985753
5        20.0                  5                 1          0.985534
6        20.0                  2                 2          0.982795
7        20.0                  5                 2          0.982664
0        10.0                  2                 1          0.965037
2        10.0                  2                 2          0.964658
1        10.0                  5                 1          0.965022
3        10.0                  5                 2          0.964658
8         NaN                  2                 1          0.999971
9         NaN                  5                 1          0.997888
11        NaN                  5                 2          0.983961
10        NaN                  2                 2          0.984791

    mean_test_score  rank_test_score
4          0.965066                1
5          0.964862                2
6          0.963813                3
7          0.963609                4
0          0.959064                5
2          0.959064                6
1          0.958948                7
3          0.958802                8
8          0.945225                9
9          0.944555               10
11         0.936600               11
10         0.935668               12

In [90]:
from sklearn.metrics import confusion_matrix, classification_report

# Get best model from GridSearch
best_model = grid_dt.best_estimator_

# Predict on test set
y_pred_dt_tuned = best_model.predict(X_test_vec)

# Evaluation
print(confusion_matrix(y_test, y_pred_dt_tuned))
print(classification_report(y_test, y_pred_dt_tuned))

[[6932  997]
 [ 227 8342]]
              precision    recall  f1-score   support

           0       0.97      0.87      0.92      7929
           1       0.89      0.97      0.93      8569

    accuracy                           0.93     16498
   macro avg       0.93      0.92      0.93     16498
weighted avg       0.93      0.93      0.93     16498

# 5. Logistic Regression

In [91]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

lr_en = LogisticRegression(
    penalty='elasticnet',
    solver='saga',
    l1_ratio=0.5,   # mix of L1 and L2
    C=1,
    max_iter=2000,
    random_state=42
)

lr_en.fit(X_train_vec, y_train)

y_pred = lr_en.predict(X_test_vec)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

d:\2. Cyber Security\Term Project\New folder\cybersec_1\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

[[7732  197]
 [ 105 8464]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      7929
           1       0.98      0.99      0.98      8569

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498

In [92]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
import pandas as pd

param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.2, 0.5, 0.8]
}

grid_lr_en = GridSearchCV(
    LogisticRegression(
        penalty='elasticnet',
        solver='saga',
        max_iter=2000,
        random_state=42
    ),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

# Train
grid_lr_en.fit(X_train_vec, y_train)

# Best result
print("Best parameters:", grid_lr_en.best_params_)
print("Best recall:", grid_lr_en.best_score_)

# Convert results to DataFrame
df = pd.DataFrame(grid_lr_en.cv_results_)

# Expand params into columns
params_df = pd.json_normalize(df['params'])

# Combine
df_full = pd.concat([params_df, df], axis=1)

# Select relevant columns
df_results = df_full[['C', 'l1_ratio', 'mean_train_score', 'mean_test_score', 'rank_test_score']]

# Sort
df_results = df_results.sort_values(by='rank_test_score')

print("\nAll parameter combinations:")
print(df_results)

d:\2. Cyber Security\Term Project\New folder\cybersec_1\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

Best parameters: {'C': 10, 'l1_ratio': 0.2}
Best recall: 0.9889575335220385

All parameter combinations:
        C  l1_ratio  mean_train_score  mean_test_score  rank_test_score
9   10.00       0.2          0.998077         0.988958                1
10  10.00       0.5          0.998383         0.988608                2
11  10.00       0.8          0.998864         0.987588                3
6    1.00       0.2          0.991653         0.987297                4
7    1.00       0.5          0.990633         0.986161                5
8    1.00       0.8          0.989511         0.985403                6
3    0.10       0.2          0.981222         0.979605                7
2    0.01       0.8          0.977274         0.977157                8
4    0.10       0.5          0.977187         0.976196                9
0    0.01       0.2          0.974462         0.974244               10
1    0.01       0.5          0.973064         0.972962               11
5    0.10       0.8          0.971971         0.970660               12

In [93]:
from sklearn.metrics import confusion_matrix, classification_report

# Get best model from GridSearch
best_model = grid_lr_en.best_estimator_

# Predict on test set
y_pred_lr= best_model.predict(X_test_vec)

# Evaluation
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

[[7799  130]
 [  91 8478]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7929
           1       0.98      0.99      0.99      8569

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

# Model Comparison (Multinomial Naive Bayes, Linear SVC, Random Forest, Decision Tree, Logistic Regression)

In [94]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# Put model names and predictions here
model_predictions = {
    'Multinomial Naive Bayes': y_pred_nb,
    'Linear SVC': y_pred_svc,
    'Random Forest': y_pred_rf,
    'Decision Tree': y_pred_dt,
    'Logistic Regression': y_pred_lr
}

results = []

for model_name, y_pred in model_predictions.items():
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    
    results.append({
        'Model': model_name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision (Class 1)': precision_score(y_test, y_pred, pos_label=1),
        'Recall (Class 1)': recall_score(y_test, y_pred, pos_label=1),
        'F1-score (Class 1)': f1_score(y_test, y_pred, pos_label=1),
        'False Positives': fp,
        'False Negatives': fn
    })

comparison_df = pd.DataFrame(results)
comparison_df = comparison_df.sort_values(by='Recall (Class 1)', ascending=False)
comparison_df = comparison_df.round(2)

print(comparison_df)

                     Model  Accuracy  Precision (Class 1)  Recall (Class 1)  \
4      Logistic Regression      0.99                 0.98              0.99
1               Linear SVC      0.99                 0.99              0.99
2            Random Forest      0.94                 0.90              0.99
3            Decision Tree      0.95                 0.95              0.96
0  Multinomial Naive Bayes      0.96                 0.99              0.94

   F1-score (Class 1)  False Positives  False Negatives
4                0.99              130               91
1                0.99              129               96
2                0.94              901              120
3                0.96              415              354
0                0.96              111              550

In [95]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import pickle

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('model', LogisticRegression(
        penalty='elasticnet',
        solver='saga',
        C=10,
        l1_ratio=0.2,
        max_iter=2000,
        random_state=42
    ))
])

pipeline.fit(X_train, y_train)

# Save
with open("final_model_1.pkl", "wb") as f:
    pickle.dump(pipeline, f)

d:\2. Cyber Security\Term Project\New folder\cybersec_1\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

In [96]:
with open("final_model_1.pkl", "rb") as f:
    model = pickle.load(f)

y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7810  119]
 [  65 8504]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7929
           1       0.99      0.99      0.99      8569

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

# Test with real text

In [97]:
new_text = ["free money now click here"]

prediction = model.predict(new_text)

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print(label)

Phishing

In [98]:
samples = [
    "meeting scheduled tomorrow",
    "urgent click this link now",
    "your bank account is safe",
    "win free prize now"
]

preds = model.predict(samples)

for text, pred in zip(samples, preds):
    label = "Phishing" if pred == 1 else "Legitimate"
    print(f"{text} → {label}")

meeting scheduled tomorrow → Legitimate
urgent click this link now → Phishing
your bank account is safe → Phishing
win free prize now → Phishing

In [99]:
example_text = ["""
dear customer your natwest online information has been flagged for routine check and this requires your attention
as part of our new security system we will be screening activity in the natwest system
we recently contacted you after noticing an issue on your account
we requested information from you for some reason
click here to continue
member services learn more about natwest online system
"""]

prediction = model.predict(example_text)

print("Prediction:", prediction[0])

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Prediction: 1
Label: Phishing

In [100]:
example_text = ["""Tech Dean Office <tech_deanoffice@ait.asia>
Call for Urgent Applications | Summer School on AI & Space Sciences, Moscow | Deadline: 20 April 2026
Summer School on AI & Space Sciences
Peoples' Friendship University of Russia (RUDN University), Moscow
12 September 28 September 2026 WHAT IS COVERED (FREE OF CHARGE)
Tuition  fully waived
Hostel accommodation in Moscow provided by RUDN
Local transfers in Moscow provided by RUDN

Students are responsible for international airfare and personal meals.
PROGRAM OVERVIEW
Week 1 AI Essentials: Foundations of Artificial Intelligence and Machine Learning
Week 2 AI in Action: Applications of AI in satellite data interpretation and space exploration
━━━━━━━━━━━━━━━━━━━━━━
HOW TO APPLY
Candidates must be nominated by AIT. Please complete the application form below and submit it to the FAST Dean's Office by:
DEADLINE: 20 April 2026
Application Form: [Application Form]
Shortlisted candidates will be contacted for institutional nomination.

Do not miss this opportunity to gain cutting-edge skills in AI and Space Sciences — at virtually no cost!

For inquiries, please contact the FAST Dean's Office at tech_deanoffice@ait.ac.th

"""]

prediction = model.predict(example_text)

print("Prediction:", prediction[0])

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Prediction: 0
Label: Legitimate

In [101]:
import re

#url_pattern = r'(https?://\S+|www\.\S+)'
url_pattern = r'(?:https?://\S+|www\.\S+)'

# check in original text/body/subject columns
print("URLs in df_merge body:", df_merge["body"].astype(str).str.contains(url_pattern, regex=True, na=False).sum())
print("URLs in df_merge text:", df_merge["text"].astype(str).str.contains(url_pattern, regex=True, na=False).sum())

print("URLs in df_merge_1 body:", df_merge_1["body"].astype(str).str.contains(url_pattern, regex=True, na=False).sum())
print("URLs in df_merge_1 text:", df_merge_1["text"].astype(str).str.contains(url_pattern, regex=True, na=False).sum())

URLs in df_merge body: 0
URLs in df_merge text: 0
URLs in df_merge_1 body: 32776
URLs in df_merge_1 text: 32789

# Try to check URL link too

In [102]:
df_merge["raw_text"] = df_merge["text"]
df_merge_1["raw_text"] = df_merge_1["text"]

# Extract URL features from raw_text

In [103]:
import re
import pandas as pd
from urllib.parse import urlparse

url_pattern = r'(?:https?://\S+|www\.\S+)'

def extract_urls(text):
    if pd.isna(text):
        return []
    return re.findall(url_pattern, str(text))

def url_features(text):
    urls = extract_urls(text)

    num_urls = len(urls)
    has_url = 1 if num_urls > 0 else 0
    has_http = 0
    has_ip = 0
    suspicious_tld = 0
    suspicious_word = 0
    many_hyphens = 0

    suspicious_patterns = [
        r"login", r"verify", r"secure", r"account",
        r"confirm", r"update", r"signin", r"auth", r"bank"
    ]

    suspicious_tlds = [".xyz", ".top", ".ru", ".tk", ".ml", ".cf", ".gq"]

    for u in urls:
        full_url = u if u.startswith(("http://", "https://")) else "http://" + u

        # clean common junk characters attached to URLs
        full_url = full_url.strip(" \t\n\r<>\"'(),;[]{}")

        try:
            parsed = urlparse(full_url)
            domain = parsed.netloc.lower()
        except ValueError:
            continue

        if not domain:
            continue

        # HTTP vs HTTPS
        if parsed.scheme == "http":
            has_http = 1

        # IPv4 address detection
        if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", domain):
            has_ip = 1

        # suspicious TLD
        if any(domain.endswith(tld) for tld in suspicious_tlds):
            suspicious_tld = 1

        # many hyphens
        if domain.count("-") >= 2:
            many_hyphens = 1

        # suspicious keyword pattern in domain
        if any(re.search(p, domain) for p in suspicious_patterns):
            suspicious_word = 1

    return pd.Series({
        "num_urls": num_urls,
        "has_url": has_url,
        "has_http": has_http,
        "has_ip": has_ip,
        "suspicious_tld": suspicious_tld,
        "suspicious_word": suspicious_word,
        "many_hyphens": many_hyphens
    })

In [104]:
url_feat_merge = df_merge["raw_text"].apply(url_features)
url_feat_merge_1 = df_merge_1["raw_text"].apply(url_features)

df_merge = pd.concat([df_merge, url_feat_merge], axis=1)
df_merge_1 = pd.concat([df_merge_1, url_feat_merge_1], axis=1)

# just checking the broken URLs

In [105]:
bad_urls = []

for text in df_merge_1["raw_text"].dropna():
    urls = extract_urls(text)
    for u in urls:
        full_url = u if u.startswith(("http://", "https://")) else "http://" + u
        full_url = full_url.strip(" \t\n\r<>\"'(),;[]{}")
        try:
            urlparse(full_url)
        except ValueError:
            bad_urls.append(full_url)

print("Number of bad URLs:", len(bad_urls))
print(bad_urls[:20])

Number of bad URLs: 7
['http://www.tradelinkllc.com"]:', 'http://www.tradelinkllc.com"]:', 'http://www.tradelinkllc.com"]:', 'http://www.tradelinkllc.com"]:', 'http://[a-z]{8,}\\\\d{5,}\\\\.blogspot\\\\.com/$', 'http://[a-z]{8,}\\\\d{5,}\\\\.blogspot\\\\.com/$', 'http://www.soft2reg](http://www.soft2reg.com/images/logo.gif']

In [106]:
print(df_merge[["num_urls", "has_url", "has_http", "has_ip", "suspicious_tld", "suspicious_word", "many_hyphens"]].head())
print(df_merge_1[["num_urls", "has_url", "has_http", "has_ip", "suspicious_tld", "suspicious_word", "many_hyphens"]].head())

   num_urls  has_url  has_http  has_ip  suspicious_tld  suspicious_word  \
0         0        0         0       0               0                0
1         0        0         0       0               0                0
2         0        0         0       0               0                0
3         0        0         0       0               0                0
4         0        0         0       0               0                0

   many_hyphens
0             0
1             0
2             0
3             0
4             0
   num_urls  has_url  has_http  has_ip  suspicious_tld  suspicious_word  \
0         1        1         1       0               0                0
1         1        1         1       0               0                0
2        24        1         1       0               0                0
3       652        1         1       0               1                0
4         1        1         1       0               0                0

   many_hyphens
0             0
1             0
2             0
3             0
4             0

In [107]:
df_final = pd.concat([
    df_merge[["clean_text", "label", "num_urls", "has_url", "has_http", "has_ip", "suspicious_tld", "suspicious_word", "many_hyphens"]],
    df_merge_1[["clean_text", "label", "num_urls", "has_url", "has_http", "has_ip", "suspicious_tld", "suspicious_word", "many_hyphens"]]
], ignore_index=True)

In [108]:
print(df_final.shape)
df_final.head()

(82486, 9)

,clean_text,label,num_urls,has_url,has_http,has_ip,suspicious_tld,suspicious_word,many_hyphens
0,hpl nom may 25 2001 see attached file hplno 52...,0,0,0,0,0,0,0,0
1,nom actual vols 24 th forwarded sabrae zajac h...,0,0,0,0,0,0,0,0
2,enron actuals march 30 april 1 201 estimated a...,0,0,0,0,0,0,0,0
3,hpl nom may 30 2001 see attached file hplno 53...,0,0,0,0,0,0,0,0
4,hpl nom june 1 2001 see attached file hplno 60...,0,0,0,0,0,0,0,0

# Update 1

# Train Test Split original

In [109]:
from sklearn.model_selection import train_test_split

X = df_final[[
    "clean_text",
    "num_urls",
    "has_url",
    "has_http",
    "has_ip",
    "suspicious_tld",
    "suspicious_word",
    "many_hyphens"
]]

y = df_final["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Build the hybrid model

In [110]:
#from sklearn.compose import ColumnTransformer
#from sklearn.pipeline import Pipeline
#from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.linear_model import LogisticRegression

#preprocessor = ColumnTransformer(
    #transformers=[
        #(
            #"tfidf",
            #TfidfVectorizer(
                #max_features=10000,
                #min_df=5,
                #max_df=0.95,
                #ngram_range=(1,2),
                #token_pattern=r'\b[a-zA-Z]{2,}\b'
            #),
            #"clean_text"
        #),
        #(
            #"url_features",
            #"passthrough",
            #["num_urls", "has_url", "has_http", "has_ip",
            # "suspicious_tld", "suspicious_word", "many_hyphens"]
        #)
    #]
#)

#model = Pipeline([
    #("features", preprocessor),
    #("clf", LogisticRegression(
        #penalty="elasticnet",
        #solver="saga",
        #C=10,
        #l1_ratio=0.2,
        #max_iter=2000,
        #random_state=42
    #))
#])
#model.fit(X_train, y_train)

In [111]:
#print(df_final[["num_urls", "suspicious_word", "suspicious_tld"]].describe())

In [114]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    min_df=5,
    max_df=0.95,
    ngram_range=(1, 2),
    token_pattern=r'\b[a-zA-Z]{2,}\b'
)

X_train_vec = vectorizer.fit_transform(X_train["clean_text"])
X_test_vec = vectorizer.transform(X_test["clean_text"])

In [115]:
from scipy.sparse import csr_matrix

url_cols = [
    "num_urls", "has_url", "has_http", "has_ip",
    "suspicious_tld", "suspicious_word", "many_hyphens"
]

X_train_url = csr_matrix(X_train[url_cols].values)
X_test_url = csr_matrix(X_test[url_cols].values)

In [116]:
from scipy.sparse import hstack

X_train_hybrid = hstack([X_train_vec, X_train_url])
X_test_hybrid = hstack([X_test_vec, X_test_url])

In [117]:
print(X_train_hybrid.shape)
print(X_test_hybrid.shape)

(65988, 10007)
(16498, 10007)

In [118]:
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, classification_report

svc_hybrid = LinearSVC(
    C=1,
    random_state=42,
    max_iter=5000
)

svc_hybrid.fit(X_train_hybrid, y_train)

y_pred_svc_hybrid = svc_hybrid.predict(X_test_hybrid)

print(confusion_matrix(y_test, y_pred_svc_hybrid))
print(classification_report(y_test, y_pred_svc_hybrid))

[[7804  115]
 [  79 8500]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7919
           1       0.99      0.99      0.99      8579

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

In [119]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC
import pandas as pd

param_grid = {
    'C': [0.01, 0.1, 1, 10]
}

grid_svc_hybrid = GridSearchCV(
    LinearSVC(random_state=42, max_iter=5000),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1,
    return_train_score=True
)

grid_svc_hybrid.fit(X_train_hybrid, y_train)

print("Best parameters:", grid_svc_hybrid.best_params_)
print("Best recall:", grid_svc_hybrid.best_score_)

df = pd.DataFrame(grid_svc_hybrid.cv_results_)
params_df = pd.json_normalize(df['params'])
df_full = pd.concat([params_df, df], axis=1)

df_results = df_full[['C', 'mean_train_score', 'mean_test_score', 'rank_test_score']]
df_results = df_results.sort_values(by='rank_test_score')

print(df_results)

Best parameters: {'C': 1}
Best recall: 0.9891874622107159
       C  mean_train_score  mean_test_score  rank_test_score
2   1.00          0.998382         0.989187                1
1   0.10          0.993195         0.988721                2
3  10.00          0.999971         0.986594                3
0   0.01          0.985574         0.983679                4

In [120]:
import re
import pandas as pd
from urllib.parse import urlparse
from scipy.sparse import csr_matrix, hstack

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
import pickle

df_final_raw = pd.concat([
    df_merge[["raw_text", "label"]],
    df_merge_1[["raw_text", "label"]]
], ignore_index=True)

from sklearn.model_selection import train_test_split


X = df_final_raw["raw_text"]
y = df_final_raw["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# -----------------------------
# 1. Text cleaning function
# -----------------------------
url_pattern = r'(?:https?://\S+|www\.\S+)'
def clean_text(text):
    text = str(text).lower()

# replace urls with placeholder
    text = re.sub(url_pattern, ' urltoken ', text)
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


# -----------------------------
# 2. URL feature extraction
# -----------------------------


def extract_urls(text):
    if pd.isna(text):
        return []
    return re.findall(url_pattern, str(text))

#def url_features(text):
    #urls = extract_urls(text)

    #num_urls = len(urls)
    #has_url = 1 if num_urls > 0 else 0
    #has_http = 0
    #has_ip = 0
    #suspicious_tld = 0
    #suspicious_word = 0
    #many_hyphens = 0

    #suspicious_patterns = [
        #r"login", r"verify", r"secure", r"account",
        #r"confirm", r"update", r"signin", r"auth", r"bank"
    #]

    #suspicious_tlds = [".xyz", ".top", ".ru", ".tk", ".ml", ".cf", ".gq"]

    #for u in urls:
        #full_url = u if u.startswith(("http://", "https://")) else "http://" + u
        #full_url = full_url.strip(" \t\n\r<>\"'(),;[]{}")

        #try:
            #parsed = urlparse(full_url)
            #domain = parsed.netloc.lower()
        #except ValueError:
            #continue

        #if not domain:
            #continue

        #if parsed.scheme == "http":
            #has_http = 1

        #if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", domain):
            #has_ip = 1

        #if any(domain.endswith(tld) for tld in suspicious_tlds):
            #suspicious_tld = 1

        #if domain.count("-") >= 2:
            #many_hyphens = 1

        #if any(re.search(p, domain) for p in suspicious_patterns):
            #suspicious_word = 1

    #return [
        #num_urls, has_url, has_http, has_ip,
        #suspicious_tld, suspicious_word, many_hyphens
    #]


# Update Code
def url_features(text):
    urls = extract_urls(text)

    num_urls = len(urls)
    has_url = 1 if num_urls > 0 else 0
    has_http = 0
    has_ip = 0
    suspicious_tld = 0
    suspicious_word = 0
    many_hyphens = 0

    suspicious_patterns = [
        r"login", r"verify", r"secure", r"account",
        r"confirm", r"update", r"signin", r"auth", r"bank"
    ]

    suspicious_tlds = [".xyz", ".top", ".ru", ".tk", ".ml", ".cf", ".gq"]

    for u in urls:
        original_url = u.strip(" \t\n\r<>\"'(),;[]{}")
        full_url = original_url if original_url.startswith(("http://", "https://")) else "http://" + original_url

        try:
            parsed = urlparse(full_url)
            domain = parsed.netloc.lower()
        except ValueError:
            continue

        if not domain:
            continue

        # only mark has_http if the ORIGINAL text explicitly used http://
        if original_url.lower().startswith("http://"):
            has_http = 1

        if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", domain):
            has_ip = 1

        if any(domain.endswith(tld) for tld in suspicious_tlds):
            suspicious_tld = 1

        if domain.count("-") >= 2:
            many_hyphens = 1

        if any(re.search(p, domain) for p in suspicious_patterns):
            suspicious_word = 1

    return [
        num_urls, has_url, has_http, has_ip,
        suspicious_tld, suspicious_word, many_hyphens
    ]



# -----------------------------
# 3. Custom hybrid transformer
# -----------------------------
class HybridTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, max_features=10000, min_df=5, max_df=0.95, ngram_range=(1, 2)):
        self.max_features = max_features
        self.min_df = min_df
        self.max_df = max_df
        self.ngram_range = ngram_range
        self.vectorizer = TfidfVectorizer(
            max_features=self.max_features,
            min_df=self.min_df,
            max_df=self.max_df,
            ngram_range=self.ngram_range,
            token_pattern=r'\b[a-zA-Z]{2,}\b',
            stop_words='english'
        )

    def fit(self, X, y=None):
        cleaned_texts = [clean_text(x) for x in X]
        self.vectorizer.fit(cleaned_texts)
        return self

    def transform(self, X):
        cleaned_texts = [clean_text(x) for x in X]
        text_vec = self.vectorizer.transform(cleaned_texts)

        #url_feat_matrix = csr_matrix([url_features(x) for x in X])

        url_feat_matrix = csr_matrix([url_features(x) for x in X], dtype=float)

        #hybrid = hstack([text_vec, url_feat_matrix])
        #return hybrid

        return hstack([text_vec, url_feat_matrix])


# -----------------------------
# 4. Build full pipeline
# -----------------------------
hybrid_pipeline = Pipeline([
    ('hybrid_features', HybridTransformer(
        max_features=10000,
        min_df=5,
        max_df=0.95,
        ngram_range=(1, 2)
    )),
    ('model', LinearSVC(
        C=1,
        random_state=42,
        max_iter=5000
    ))
])


# -----------------------------
# 5. Train on RAW text input
# -----------------------------
hybrid_pipeline.fit(X_train, y_train)

y_pred = hybrid_pipeline.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7809  110]
 [  90 8489]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7919
           1       0.99      0.99      0.99      8579

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

In [121]:
# -----------------------------
# 6. Save full pipeline
# -----------------------------
with open("hybrid_svc_full_pipeline.pkl", "wb") as f:
    pickle.dump(hybrid_pipeline, f)

In [122]:
import pickle
from sklearn.metrics import confusion_matrix, classification_report

with open("hybrid_svc_full_pipeline.pkl", "rb") as f:
    loaded_pipeline = pickle.load(f)

y_pred = loaded_pipeline.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[7809  110]
 [  90 8489]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7919
           1       0.99      0.99      0.99      8579

    accuracy                           0.99     16498
   macro avg       0.99      0.99      0.99     16498
weighted avg       0.99      0.99      0.99     16498

In [123]:
sample = ["""Details of the trip are as follows:
First trip
Date:April 4th , 2026 (Saturday)
Vehicle: Song Thew (13 Seats)
Departure: 9:30 am from AITCC
Return: 11:30 am from Talaad Thai
Meeting Time: 9:15 am at AIT Square (Sharp)

Second trip 
Date: April 5th, 2026 (Sunday)
Vehicle: Song Thew (13 Seats)
Departure: 9:30 am from AITCC
Return: 11:30 am from Talaad Thai
Meeting Time: 9:15 am at AIT Square (Sharp)

Please be punctual. The van will depart on time and will not wait for late arrivals.  Please note that this provision refers to those who apply through the form. Walk-ins will not be accommodated on the morning of the trip.
Selected participants will be notified through email. This Trip is free for Students
To ensure fairness and wider participation, priority will be given to students who have not yet joined the Taalad Thai trip during this semester.
No-Show Policy:
Students who register but do not attend the trip without notifying us before 8 pm tonight will be barred from the next four trips. This policy ensures fairness and efficient planning.

We look forward to your participation!"""]

prediction = loaded_pipeline.predict(sample)

print("Prediction:", prediction[0])

label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Prediction: 0
Label: Legitimate

In [124]:
sample_url = ["https://www.kaggle.com/datasets/naserabdullahalam/phishing-email-dataset/data"]
prediction = loaded_pipeline.predict(sample_url)
print("Prediction:", prediction[0])
label = "Phishing" if prediction[0] == 1 else "Legitimate"
print("Label:", label)

Prediction: 1
Label: Phishing

In [125]:
feature_names = hybrid_pipeline.named_steps['hybrid_features'].vectorizer.get_feature_names_out()
url_feature_names = [
    "num_urls", "has_url", "has_http", "has_ip",
    "suspicious_tld", "suspicious_word", "many_hyphens"
]

all_features = list(feature_names) + url_feature_names
coefs = hybrid_pipeline.named_steps['model'].coef_[0]

top_phishing = sorted(zip(all_features, coefs), key=lambda x: x[1], reverse=True)[:20]
top_legit = sorted(zip(all_features, coefs), key=lambda x: x[1])[:20]

print("Top phishing features:")
for f, w in top_phishing:
    print(f, w)

print("\nTop legitimate features:")
for f, w in top_legit:
    print(f, w)

Top phishing features:
kindly 2.388625775112295
investment 2.260598853563106
remove 2.2140885254553546
meds 2.176927133500557
http 2.072579719257518
com 2.0722509919495593
life 1.932323541492202
jose 1.8431268740618054
monkey org 1.738019840329147
watches 1.7372085705567126
cheap 1.6993531415845022
mobile email 1.6817425176899858
click 1.655633159220013
lose 1.63164212362771
love 1.620142655913959
expire 1.6099412064909309
immediately 1.6081691144157562
remedy 1.6050740032570587
spamassassin sightings 1.6015379467237392
dimensions 1.6008912534089725

Top legitimate features:
enron -6.0042852984612285
wrote -5.041538639648922
vince -3.757590941914373
opensuse -3.3934178133820376
louise -3.2745907050279563
thanks -3.096245306527272
university -2.7766293865473015
forwarded -2.6532131427764565
gmail com -2.616608064561388
fork -2.446384314116613
kaminski -2.4141590663363908
uai -2.3798086592155094
nz -2.355666681315022
enron com -2.3244419764241857
com address -2.3040676797313964
policy urltoken -2.2058415071287176
net unknown -2.1920584454742253
attached -2.1909280342524298
perl -2.1418616176214758
spamassassin -2.1407054288012084

In [ ]:
print(df_final.columns)

Index(['clean_text', 'label', 'num_urls', 'has_url', 'has_http', 'has_ip',
       'suspicious_tld', 'suspicious_word', 'many_hyphens'],
      dtype='str')

In [ ]:
df_final.head()

,clean_text,label,num_urls,has_url,has_http,has_ip,suspicious_tld,suspicious_word,many_hyphens
0,hpl nom may 25 2001 see attached file hplno 52...,0,0,0,0,0,0,0,0
1,nom actual vols 24 th forwarded sabrae zajac h...,0,0,0,0,0,0,0,0
2,enron actuals march 30 april 1 201 estimated a...,0,0,0,0,0,0,0,0
3,hpl nom may 30 2001 see attached file hplno 53...,0,0,0,0,0,0,0,0
4,hpl nom june 1 2001 see attached file hplno 60...,0,0,0,0,0,0,0,0

In [126]:
sample = ["https://chatgpt.com/"]

print("Cleaned text:", clean_text(sample[0]))
print("URL features:", url_features(sample[0]))

Cleaned text: urltoken
URL features: [1, 1, 0, 0, 0, 0, 0]